103-dig_the-data

diff --git a/0x04-loops_conditions_and_parsing/103-dig_the-data b/0x04-loops_conditions_and_parsing/103-dig_the-data
--- a/0x04-loops_conditions_and_parsing/103-dig_the-data
+++ b/0x04-loops_conditions_and_parsing/103-dig_the-data
@@ -1,12 +1,11 @@
-#!/user/bin/env bash
-# Parses Apache log files in list format.
-#  Groups visitors by IP and HTTP status code.
-#  Displays the number of occurrences, IP, and HTTP status
-#+ code of each log, in sorted order.
+!/usr/bin/env bash
 
-awk '{print $1 " " $9}' apache-access.log | sort| uniq -c | sort -rn
+# Check if the log file exists
+if [ ! -f "apache-access.log" ]; then
+    echo "Error: Apache log file 'apache-access.log' not found!"
+    exit 1
+fi
 
-
-
-
-
+# Parse Apache log file, group visitors by IP and HTTP status code,
+# and display the number of occurrences along with IP and HTTP status code in sorted order.
+awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
